---
- name: 'global_parameters | Configure global parameters'
  redhat.satellite.global_parameter:
    username: '{{ _satellite_username }}'
    password: '{{ _satellite_password }}'
    server_url: '{{ _satellite_server_url }}'
    validate_certs: '{{ _satellite_validate_certs }}'
    name: '{{ __t_param.name }}'
    value: '{{ __t_param.value }}'
    parameter_type: '{{ __t_param.parameter_type | default(omit) }}'
    hidden_value: '{{ __t_param.hidden_value | default(omit) }}'
    state: 'present'
  no_log: '{{ __t_param.hidden_value is defined }}'
  loop: '{{ _sat_global_parameters }}'
  loop_control:
    loop_var: '__t_param'
    label: '{{ __t_param.name }}'
...
